filter:
  excluded_paths: [framework/*, locale/*, docs/*, fonts/*, third_party/*, application/third_party/*]
tools:
    php_mess_detector:
        config:
            controversial_rules: { camel_case_class_name: true, camel_case_property_name: true, camel_case_method_name: true, camel_case_parameter_name: true, camel_case_variable_name: true }